from setuptools import setup

setup(
    name='Pyramid-REST-API',
    version='',
    packages=['interpreter.Lib.site-packages.zope.interface', 'interpreter.Lib.site-packages.zope.interface.tests',
              'interpreter.Lib.site-packages.zope.interface.common',
              'interpreter.Lib.site-packages.zope.interface.common.tests',
              'interpreter.Lib.site-packages.zope.sqlalchemy', 'interpreter.Lib.site-packages.zope.deprecation',
              'interpreter.Lib.site-packages.paste.deploy', 'interpreter.Lib.site-packages.webob',
              'interpreter.Lib.site-packages.hupper', 'interpreter.Lib.site-packages.jinja2',
              'interpreter.Lib.site-packages.repoze.lru', 'interpreter.Lib.site-packages.plaster',
              'interpreter.Lib.site-packages.pyramid', 'interpreter.Lib.site-packages.pyramid.tests',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.ccbugapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.eventonly',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.hybridapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.localeapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.fixtureapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.fixtureapp.subpackage',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.permbugapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.restbugapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.conflictapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.includeapp1',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.wsgiapp2app',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.forbiddenapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.notfoundview',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.defpermbugapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.forbiddenview',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.staticpermapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.subrequestapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.static_abspath',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.rendererscanapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.rendererscanapp.two',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.exceptionviewapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.static_assetspec',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.viewdecoratorapp',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.viewdecoratorapp.views',
              'interpreter.Lib.site-packages.pyramid.tests.pkgs.static_routeprefix',
              'interpreter.Lib.site-packages.pyramid.tests.test_config',
              'interpreter.Lib.site-packages.pyramid.tests.test_config.path.scanerror',
              'interpreter.Lib.site-packages.pyramid.tests.test_config.pkgs',
              'interpreter.Lib.site-packages.pyramid.tests.test_config.pkgs.asset',
              'interpreter.Lib.site-packages.pyramid.tests.test_config.pkgs.asset.subpackage',
              'interpreter.Lib.site-packages.pyramid.tests.test_config.pkgs.selfscan',
              'interpreter.Lib.site-packages.pyramid.tests.test_config.pkgs.scannable',
              'interpreter.Lib.site-packages.pyramid.tests.test_config.pkgs.scannable.subpackage',
              'interpreter.Lib.site-packages.pyramid.tests.test_config.pkgs.scannable.subpackage.subsubpackage',
              'interpreter.Lib.site-packages.pyramid.tests.test_config.pkgs.scanextrakw',
              'interpreter.Lib.site-packages.pyramid.tests.test_scripts',
              'interpreter.Lib.site-packages.pyramid.tests.test_scaffolds',
              'interpreter.Lib.site-packages.pyramid.config', 'interpreter.Lib.site-packages.pyramid.scripts',
              'interpreter.Lib.site-packages.pyramid.scaffolds',
              'interpreter.Lib.site-packages.pyramid.scaffolds.zodb.+package+',
              'interpreter.Lib.site-packages.pyramid.scaffolds.alchemy.+package+',
              'interpreter.Lib.site-packages.pyramid.scaffolds.alchemy.+package+.views',
              'interpreter.Lib.site-packages.pyramid.scaffolds.alchemy.+package+.scripts',
              'interpreter.Lib.site-packages.pyramid.scaffolds.starter.+package+',
              'interpreter.Lib.site-packages.psycopg2', 'interpreter.Lib.site-packages.psycopg2.tests',
              'interpreter.Lib.site-packages.venusian', 'interpreter.Lib.site-packages.venusian.tests',
              'interpreter.Lib.site-packages.venusian.tests.fixtures',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.one',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.pyc',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.pyc.subpackage',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.two',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.nested',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.nested.sub1',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.nested.sub1.subsub1',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.nested.sub2',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.nested.sub2.subsub2',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.attrerror',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.importonly',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.importerror',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.subpackages',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.subpackages.childpackage',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.import_and_scan',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.attrerror_package',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.attrerror_package.will_cause_import_error',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.importerror_package',
              'interpreter.Lib.site-packages.venusian.tests.fixtures.importerror_package.will_cause_import_error',
              'interpreter.Lib.site-packages.markupsafe', 'interpreter.Lib.site-packages.sqlalchemy',
              'interpreter.Lib.site-packages.sqlalchemy.ext',
              'interpreter.Lib.site-packages.sqlalchemy.ext.declarative',
              'interpreter.Lib.site-packages.sqlalchemy.orm', 'interpreter.Lib.site-packages.sqlalchemy.sql',
              'interpreter.Lib.site-packages.sqlalchemy.util', 'interpreter.Lib.site-packages.sqlalchemy.event',
              'interpreter.Lib.site-packages.sqlalchemy.engine', 'interpreter.Lib.site-packages.sqlalchemy.testing',
              'interpreter.Lib.site-packages.sqlalchemy.testing.suite',
              'interpreter.Lib.site-packages.sqlalchemy.testing.plugin',
              'interpreter.Lib.site-packages.sqlalchemy.dialects',
              'interpreter.Lib.site-packages.sqlalchemy.dialects.mssql',
              'interpreter.Lib.site-packages.sqlalchemy.dialects.mysql',
              'interpreter.Lib.site-packages.sqlalchemy.dialects.oracle',
              'interpreter.Lib.site-packages.sqlalchemy.dialects.sqlite',
              'interpreter.Lib.site-packages.sqlalchemy.dialects.sybase',
              'interpreter.Lib.site-packages.sqlalchemy.dialects.firebird',
              'interpreter.Lib.site-packages.sqlalchemy.dialects.postgresql',
              'interpreter.Lib.site-packages.sqlalchemy.databases',
              'interpreter.Lib.site-packages.sqlalchemy.connectors', 'interpreter.Lib.site-packages.transaction',
              'interpreter.Lib.site-packages.transaction.tests', 'interpreter.Lib.site-packages.pyramid_mako',
              'interpreter.Lib.site-packages.pyramid_jinja2', 'interpreter.Lib.site-packages.pyramid_jinja2.demo',
              'interpreter.Lib.site-packages.pyramid_jinja2.tests',
              'interpreter.Lib.site-packages.pyramid_jinja2.scaffolds',
              'interpreter.Lib.site-packages.translationstring',
              'interpreter.Lib.site-packages.translationstring.tests',
              'interpreter.Lib.site-packages.plaster_pastedeploy',
              'interpreter.Lib.site-packages.mako-1.0.7-py3.6.egg.mako',
              'interpreter.Lib.site-packages.mako-1.0.7-py3.6.egg.mako.ext',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'interpreter.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations',
              'interpreter.Lib.site-packages.Pygments-2.2.0-py3.6.egg.pygments',
              'interpreter.Lib.site-packages.Pygments-2.2.0-py3.6.egg.pygments.lexers',
              'interpreter.Lib.site-packages.Pygments-2.2.0-py3.6.egg.pygments.styles',
              'interpreter.Lib.site-packages.Pygments-2.2.0-py3.6.egg.pygments.filters',
              'interpreter.Lib.site-packages.Pygments-2.2.0-py3.6.egg.pygments.formatters',
              'interpreter.Lib.site-packages.waitress-1.1.0-py3.6.egg.waitress',
              'interpreter.Lib.site-packages.waitress-1.1.0-py3.6.egg.waitress.tests',
              'interpreter.Lib.site-packages.waitress-1.1.0-py3.6.egg.waitress.tests.fixtureapps',
              'interpreter.Lib.site-packages.pyramid_debugtoolbar-4.4-py3.6.egg.pyramid_debugtoolbar',
              'interpreter.Lib.site-packages.pyramid_debugtoolbar-4.4-py3.6.egg.pyramid_debugtoolbar.panels'],
    url='',
    license='',
    author='Michael Verdegaal',
    author_email='',
    description='A simple REST API created to handle users.'
)
